import type { PolicyRule } from './types.js';

export const DEFAULT_SAFE_PATTERNS: PolicyRule[] = [
  { pattern: 'npm test', policy: 'safe', reason: 'Running tests' },
  { pattern: 'npm run test', policy: 'safe', reason: 'Running tests' },
  { pattern: 'npm run lint', policy: 'safe', reason: 'Running linter' },
  { pattern: 'npm run typecheck', policy: 'safe', reason: 'Type checking' },
  { pattern: 'npm run build', policy: 'safe', reason: 'Building project' },
  { pattern: 'pnpm test', policy: 'safe', reason: 'Running tests' },
  { pattern: 'pnpm run test', policy: 'safe', reason: 'Running tests' },
  { pattern: 'pnpm lint', policy: 'safe', reason: 'Running linter' },
  { pattern: 'pnpm run lint', policy: 'safe', reason: 'Running linter' },
  { pattern: 'pnpm typecheck', policy: 'safe', reason: 'Type checking' },
  { pattern: 'pnpm run typecheck', policy: 'safe', reason: 'Type checking' },
  { pattern: 'pnpm build', policy: 'safe', reason: 'Building project' },
  { pattern: 'pnpm run build', policy: 'safe', reason: 'Building project' },
  { pattern: 'yarn test', policy: 'safe', reason: 'Running tests' },
  { pattern: 'yarn lint', policy: 'safe', reason: 'Running linter' },
  { pattern: 'yarn build', policy: 'safe', reason: 'Building project' },
  { pattern: 'tsc --noEmit', policy: 'safe', reason: 'Type checking' },
  { pattern: 'npx tsc --noEmit', policy: 'safe', reason: 'Type checking' },
  { pattern: 'npx vitest run', policy: 'safe', reason: 'Running tests' },
  { pattern: 'npx jest', policy: 'safe', reason: 'Running tests' },
  { pattern: 'npx eslint', policy: 'safe', reason: 'Running linter' },
  { pattern: 'npx prettier --check', policy: 'safe', reason: 'Checking formatting' },
  { pattern: 'git status', policy: 'safe', reason: 'Checking git status' },
  { pattern: 'git diff', policy: 'safe', reason: 'Viewing diff' },
  { pattern: 'git log', policy: 'safe', reason: 'Viewing commit log' },
  { pattern: 'git branch', policy: 'safe', reason: 'Listing branches' },
  { pattern: 'python -m pytest', policy: 'safe', reason: 'Running Python tests' },
  { pattern: 'cargo test', policy: 'safe', reason: 'Running Rust tests' },
  { pattern: 'cargo check', policy: 'safe', reason: 'Checking Rust code' },
  { pattern: 'go test', policy: 'safe', reason: 'Running Go tests' },
  { pattern: 'go vet', policy: 'safe', reason: 'Vetting Go code' },
];

export const DEFAULT_APPROVAL_PATTERNS: PolicyRule[] = [
  { pattern: 'npm install', policy: 'requires_approval', reason: 'Installing dependencies' },
  { pattern: 'pnpm add', policy: 'requires_approval', reason: 'Adding dependencies' },
  { pattern: 'pnpm install', policy: 'requires_approval', reason: 'Installing dependencies' },
  { pattern: 'yarn add', policy: 'requires_approval', reason: 'Adding dependencies' },
  { pattern: 'git commit', policy: 'requires_approval', reason: 'Creating git commit' },
  { pattern: 'git push', policy: 'requires_approval', reason: 'Pushing to remote' },
  { pattern: 'git checkout', policy: 'requires_approval', reason: 'Switching branches' },
  { pattern: 'git merge', policy: 'requires_approval', reason: 'Merging branches' },
  { pattern: 'git rebase', policy: 'requires_approval', reason: 'Rebasing' },
  { pattern: 'git stash', policy: 'requires_approval', reason: 'Stashing changes' },
  { pattern: 'pip install', policy: 'requires_approval', reason: 'Installing Python packages' },
  { pattern: 'cargo install', policy: 'requires_approval', reason: 'Installing Rust crate' },
  {
    pattern: 'npx prisma migrate',
    policy: 'requires_approval',
    reason: 'Running database migration',
  },
  { pattern: 'npx prisma db push', policy: 'requires_approval', reason: 'Pushing database schema' },
];

export const DEFAULT_BLOCKED_PATTERNS: PolicyRule[] = [
  { pattern: 'rm -rf /', policy: 'blocked', reason: 'Destructive operation' },
  { pattern: 'rm -rf ~', policy: 'blocked', reason: 'Destructive operation' },
  { pattern: 'rm -rf *', policy: 'blocked', reason: 'Destructive operation' },
  { pattern: 'rm -r /', policy: 'blocked', reason: 'Destructive operation' },
  { pattern: 'mkfs', policy: 'blocked', reason: 'Filesystem formatting' },
  { pattern: 'dd if=', policy: 'blocked', reason: 'Disk operation' },
  { pattern: 'format', policy: 'blocked', reason: 'Disk formatting' },
  { pattern: ':(){:|:&};:', policy: 'blocked', reason: 'Fork bomb' },
  { pattern: 'chmod -R 777', policy: 'blocked', reason: 'Unsafe permissions' },
  { pattern: 'curl | sh', policy: 'blocked', reason: 'Piping remote script to shell' },
  { pattern: 'curl | bash', policy: 'blocked', reason: 'Piping remote script to shell' },
  { pattern: 'wget | sh', policy: 'blocked', reason: 'Piping remote script to shell' },
  { pattern: 'git push --force', policy: 'blocked', reason: 'Force pushing' },
  { pattern: 'git push -f', policy: 'blocked', reason: 'Force pushing' },
  { pattern: 'git reset --hard', policy: 'blocked', reason: 'Destructive git reset' },
  { pattern: 'git clean -fd', policy: 'blocked', reason: 'Destructive git clean' },
  { pattern: 'git clean -xfd', policy: 'blocked', reason: 'Destructive git clean' },
  { pattern: 'sudo', policy: 'blocked', reason: 'Privilege escalation' },
  { pattern: 'chmod -R 777', policy: 'blocked', reason: 'Unsafe permissions' },
  { pattern: 'DROP TABLE', policy: 'blocked', reason: 'Destructive SQL' },
  { pattern: 'DROP DATABASE', policy: 'blocked', reason: 'Destructive SQL' },
  { pattern: 'DELETE FROM', policy: 'blocked', reason: 'Destructive SQL' },
  { pattern: 'TRUNCATE', policy: 'blocked', reason: 'Destructive SQL' },
];
